### ISSUE TITLE
Crash on load with Forge 40.0.18

### ISSUE THREAD

**Issue by iosgoodch** [onVoid/RottenLeather#1]
# Issue
With RottenLeather-1.18.2-1.2 installed, the game crashes on load with Forge 40.0.18

<img width="884" alt="Screen Shot 2022-03-16 at 10 41 07 PM" src="https://user-images.githubusercontent.com/9204465/158744598-54af4785-0ae9-4ac5-8670-ad0ff77ade31.png">

### How reproducible
Happens every time.

## Additional Information / Resources
Crash report:

[crash-2022-03-16_22.39.20-fml.txt](https://github.com/onVoid/RottenLeather/files/8281695/crash-2022-03-16_22.39.20-fml.txt)

**Comment by EldrinFal** [comment]
I'm receiving the same.
[crash-2022-03-19_22.50.05-fml.txt](https://github.com/onVoid/RottenLeather/files/8310675/crash-2022-03-19_22.50.05-fml.txt)

**Comment by brnbrd** [comment]
Looks like this is an issue with loot modifiers changing. Will get on fixing this.

**Comment by brnbrd** [comment]
Fixed with version 1.3

**Comment by iosgoodch** [comment]
Confirmed as fixed. Thank you!
